"""PDF Generator for AI Content Marketing Machine — Day 18"""

from __future__ import annotations

import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

def build_content_marketing_pdf(report: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#7c3aed'),
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=12
    )

    h2_style = ParagraphStyle(
        'H2Style',
        parent=styles['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155'),
        spaceAfter=6
    )

    story = []

    # Metadata & Header
    meta = report.get("metadata", {})
    brand_name = meta.get("brand_name", "Brand")
    topic = meta.get("weekly_topic", "Weekly Content")

    story.append(Paragraph(f"AI Content Marketing Strategy: {brand_name}", title_style))
    story.append(Paragraph(f"Topic: {topic} | Generated at: {meta.get('generated_at', '')}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0'), spaceAfter=12))

    # 1. SEO Keywords
    story.append(Paragraph("1. SEO Keyword Research", h2_style))
    seo_data = report.get("seo_keywords", {})
    keywords = seo_data.get("keywords", [])
    
    table_data = [["Keyword", "Volume", "Competition", "Intent", "Difficulty"]]
    for kw in keywords[:5]:
        table_data.append([
            kw.get("keyword", ""),
            str(kw.get("search_volume", "")),
            kw.get("competition", ""),
            kw.get("intent", ""),
            f"{kw.get('difficulty', '')}/100"
        ])

    t = Table(table_data, colWidths=[180, 70, 80, 90, 60])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#0f172a')),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))

    # 2. Blog Preview
    story.append(Paragraph("2. Long-Form Blog Post Preview", h2_style))
    blog = report.get("blog_post", {})
    story.append(Paragraph(f"<b>Title:</b> {blog.get('title', '')}", body_style))
    story.append(Paragraph(f"<b>Meta Description:</b> {blog.get('meta_description', '')}", body_style))
    story.append(Spacer(1, 8))

    # 3. Social Media
    story.append(Paragraph("3. Social Media Variants", h2_style))
    social = report.get("social_media", {})
    story.append(Paragraph(f"<b>LinkedIn Post:</b>", body_style))
    story.append(Paragraph(social.get("linkedin_post", "").replace("\n", "<br/>"), body_style))
    story.append(Spacer(1, 8))

    # 4. Email Newsletter
    story.append(Paragraph("4. Email Newsletter Options", h2_style))
    email = report.get("email_newsletter", {})
    subjects = email.get("subject_lines", [])
    for sub in subjects:
        story.append(Paragraph(f"• {sub}", body_style))
    story.append(Spacer(1, 8))

    # 5. Ad Copy & Analytics
    story.append(Paragraph("5. Performance Predictions", h2_style))
    analytics = report.get("analytics", {})
    story.append(Paragraph(f"<b>Projected Blog Views:</b> {analytics.get('projected_blog_views', 0):,}", body_style))
    story.append(Paragraph(f"<b>Projected Social Reach:</b> {analytics.get('projected_social_reach', 0):,}", body_style))
    story.append(Paragraph(f"<b>Overall Quality Score:</b> {analytics.get('overall_content_score', 0)}/100", body_style))

    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#e2e8f0'), spaceBefore=12, spaceAfter=8))
    story.append(Paragraph("Generated by Marsa Empower — AI Content Marketing Machine", subtitle_style))

    doc.build(story)
    return buffer.getvalue()
