"""ReportLab PDF builder for the AI Legal Contract System.

Generates a signature-ready PDF containing:
  - Cover page with contract metadata
  - Full legal contract text
  - Risk analysis table
  - Negotiation recommendations
  - Plain English summary
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import KeepTogether

# ---------------------------------------------------------------------------
# Color palette
# ---------------------------------------------------------------------------

NAVY     = colors.HexColor("#0F172A")
GOLD     = colors.HexColor("#D4AF37")
BLUE     = colors.HexColor("#1E40AF")
LIGHT_BG = colors.HexColor("#F8FAFC")
BORDER   = colors.HexColor("#CBD5E1")
RED_RISK = colors.HexColor("#DC2626")
YEL_RISK = colors.HexColor("#D97706")
GRN_RISK = colors.HexColor("#16A34A")

# Risk color thresholds
def risk_color(severity: int) -> colors.Color:
    if severity >= 7:
        return RED_RISK
    if severity >= 4:
        return YEL_RISK
    return GRN_RISK


# ---------------------------------------------------------------------------
# Style builder
# ---------------------------------------------------------------------------

def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle(
            "cover_title",
            fontName="Helvetica-Bold",
            fontSize=24,
            textColor=NAVY,
            alignment=TA_CENTER,
            spaceAfter=8,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub",
            fontName="Helvetica",
            fontSize=13,
            textColor=BLUE,
            alignment=TA_CENTER,
            spaceAfter=6,
        ),
        "cover_meta": ParagraphStyle(
            "cover_meta",
            fontName="Helvetica",
            fontSize=10,
            textColor=colors.HexColor("#475569"),
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=NAVY,
            spaceBefore=16,
            spaceAfter=6,
            borderPad=4,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=9,
            textColor=colors.HexColor("#1E293B"),
            alignment=TA_JUSTIFY,
            spaceAfter=5,
            leading=14,
        ),
        "bold_label": ParagraphStyle(
            "bold_label",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=NAVY,
            spaceAfter=2,
        ),
        "small_gray": ParagraphStyle(
            "small_gray",
            fontName="Helvetica-Oblique",
            fontSize=8,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=3,
        ),
        "footer": ParagraphStyle(
            "footer",
            fontName="Helvetica",
            fontSize=7,
            textColor=colors.HexColor("#94A3B8"),
            alignment=TA_CENTER,
        ),
    }


# ---------------------------------------------------------------------------
# Helper: header/footer on every page
# ---------------------------------------------------------------------------

def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # Header bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - 20 * mm, w, 20 * mm, fill=1, stroke=0)
    canvas.setFillColor(GOLD)
    canvas.rect(0, h - 22 * mm, w, 2 * mm, fill=1, stroke=0)

    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(15 * mm, h - 13 * mm, "⚖  AI Legal Contract System")
    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(w - 15 * mm, h - 13 * mm, f"CONFIDENTIAL  |  Page {doc.page}")

    # Footer
    canvas.setFillColor(BORDER)
    canvas.rect(0, 0, w, 8 * mm, fill=1, stroke=0)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.setFont("Helvetica", 7)
    canvas.drawString(15 * mm, 3 * mm, "Generated by AI Legal Contract System — Day 16 | 30 Days of AI Agents by Maryam Mumtaz")
    canvas.drawRightString(w - 15 * mm, 3 * mm, datetime.now().strftime("%Y-%m-%d %H:%M"))

    canvas.restoreState()


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _cover_page(story: list, data: dict, styles: dict) -> None:
    story.append(Spacer(1, 30 * mm))

    ct = CONTRACT_TEMPLATES_NAMES.get(data.get("contract_type", ""), data.get("contract_type", "Legal Contract").upper())
    story.append(Paragraph("AI Legal Contract System", styles["cover_sub"]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(ct, styles["cover_title"]))
    story.append(Spacer(1, 6 * mm))

    # Gold divider
    story.append(HRFlowable(width="60%", thickness=2, color=GOLD, hAlign="CENTER"))
    story.append(Spacer(1, 8 * mm))

    meta = [
        ("Parties", f"{data.get('party_a', '')}  ↔  {data.get('party_b', '')}"),
        ("Jurisdiction", data.get("jurisdiction", "")),
        ("Generated On", datetime.now().strftime("%B %d, %Y at %H:%M")),
        ("Document Status", "DRAFT — Requires Legal Review Before Execution"),
    ]
    for label, val in meta:
        story.append(Paragraph(f"<b>{label}:</b>  {val}", styles["cover_meta"]))

    story.append(Spacer(1, 10 * mm))
    story.append(HRFlowable(width="80%", thickness=0.5, color=BORDER, hAlign="CENTER"))
    story.append(Spacer(1, 6 * mm))

    # Risk summary badge
    risks = data.get("risks", [])
    high = sum(1 for r in risks if r.get("severity", 0) >= 7)
    med  = sum(1 for r in risks if 4 <= r.get("severity", 0) < 7)
    low  = sum(1 for r in risks if r.get("severity", 0) < 4)

    story.append(Paragraph(
        f"Risk Summary:  🔴 High: {high}  &nbsp; 🟡 Medium: {med}  &nbsp; 🟢 Low: {low}  &nbsp; | Total: {len(risks)} clauses reviewed",
        styles["cover_meta"]
    ))
    story.append(PageBreak())


CONTRACT_TEMPLATES_NAMES = {
    "nda": "Non-Disclosure Agreement (NDA)",
    "sla": "Service Level Agreement (SLA)",
    "employment": "Employment Contract",
    "vendor": "Vendor Agreement",
    "partnership": "Partnership Agreement",
    "freelance": "Freelance / Consulting Agreement",
    "lease": "Commercial Lease Agreement",
    "saas": "SaaS Subscription Agreement",
}


def _contract_text_section(story: list, data: dict, styles: dict) -> None:
    story.append(Paragraph("§ FULL LEGAL CONTRACT", styles["section_heading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD))
    story.append(Spacer(1, 4 * mm))

    contract_text = data.get("contract_text", "")
    for line in contract_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 2 * mm))
            continue
        # Bold headings (numbered sections or ALL CAPS lines)
        if (line[:2].strip().rstrip(".").isdigit() and len(line) < 80) or line.isupper():
            story.append(Paragraph(line, styles["bold_label"]))
        else:
            # Escape HTML special chars safely
            safe_line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe_line, styles["body"]))

    story.append(Spacer(1, 8 * mm))

    # Signature block
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("SIGNATURES", styles["bold_label"]))

    sig_data = [
        ["Party A", "", "Party B", ""],
        [f"{data.get('party_a', '_____________')}", "", f"{data.get('party_b', '_____________')}", ""],
        ["Signature: ___________________", "", "Signature: ___________________", ""],
        ["Name: ___________________", "", "Name: ___________________", ""],
        ["Title: ___________________", "", "Title: ___________________", ""],
        ["Date: ___________________", "", "Date: ___________________", ""],
    ]

    sig_table = Table(sig_data, colWidths=[70 * mm, 10 * mm, 70 * mm, 10 * mm])
    sig_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, 0), NAVY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(sig_table)
    story.append(PageBreak())


def _risk_section(story: list, data: dict, styles: dict) -> None:
    risks = data.get("risks", [])
    story.append(Paragraph("🔍 RISK ANALYSIS REPORT", styles["section_heading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD))
    story.append(Spacer(1, 4 * mm))

    if not risks:
        story.append(Paragraph("No significant risks identified by the AI Risk Reviewer.", styles["body"]))
        story.append(PageBreak())
        return

    # Category color map
    cat_colors = {
        "liability":      colors.HexColor("#FEE2E2"),
        "financial":      colors.HexColor("#FEF3C7"),
        "compliance":     colors.HexColor("#DBEAFE"),
        "ip":             colors.HexColor("#EDE9FE"),
        "termination":    colors.HexColor("#FCE7F3"),
        "confidentiality":colors.HexColor("#D1FAE5"),
        "other":          colors.HexColor("#F1F5F9"),
    }

    table_data = [["Clause", "Risk", "Severity", "Category", "Description"]]
    table_styles = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ]

    for i, risk in enumerate(risks, start=1):
        sev = risk.get("severity", 5)
        row = [
            Paragraph(risk.get("clause", ""), styles["small_gray"]),
            Paragraph(f"<b>{risk.get('risk_title', '')}</b>", styles["bold_label"]),
            Paragraph(f"<b>{sev}/10</b>", ParagraphStyle("s", fontName="Helvetica-Bold", fontSize=9, textColor=risk_color(sev), alignment=TA_CENTER)),
            Paragraph(risk.get("category", "").title(), styles["small_gray"]),
            Paragraph(risk.get("risk_description", "")[:200], styles["body"]),
        ]
        table_data.append(row)

    risk_table = Table(
        table_data,
        colWidths=[25 * mm, 35 * mm, 18 * mm, 22 * mm, 65 * mm],
        repeatRows=1,
    )
    risk_table.setStyle(TableStyle(table_styles))
    story.append(risk_table)
    story.append(PageBreak())


def _negotiation_section(story: list, data: dict, styles: dict) -> None:
    suggestions = data.get("negotiations", [])
    story.append(Paragraph("🤝 NEGOTIATION RECOMMENDATIONS", styles["section_heading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD))
    story.append(Spacer(1, 4 * mm))

    if not suggestions:
        story.append(Paragraph("No negotiation recommendations — contract is well-balanced.", styles["body"]))
        story.append(PageBreak())
        return

    for idx, s in enumerate(suggestions, 1):
        block = []
        block.append(Paragraph(
            f"{idx}. {s.get('risk_title', 'Recommendation')} — Clause {s.get('clause', '')}",
            styles["bold_label"]
        ))
        block.append(Paragraph(f"<b>Strategy:</b> {s.get('strategy', '')}", styles["body"]))
        block.append(Paragraph(
            f"<b>Suggested Language:</b> {s.get('suggested_language', '')}",
            ParagraphStyle("sug", fontName="Helvetica-Oblique", fontSize=9,
                           textColor=BLUE, leading=13, spaceAfter=4, alignment=TA_JUSTIFY)
        ))
        block.append(Paragraph(f"✅ <b>Party A Benefit:</b> {s.get('party_a_benefit', '')}", styles["small_gray"]))
        block.append(Paragraph(f"✅ <b>Party B Benefit:</b> {s.get('party_b_benefit', '')}", styles["small_gray"]))
        block.append(HRFlowable(width="100%", thickness=0.3, color=BORDER))
        block.append(Spacer(1, 3 * mm))
        story.append(KeepTogether(block))

    story.append(PageBreak())


def _plain_language_section(story: list, data: dict, styles: dict) -> None:
    translation = data.get("translation", {})
    story.append(Paragraph("📝 PLAIN LANGUAGE SUMMARY", styles["section_heading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD))
    story.append(Spacer(1, 4 * mm))

    if translation.get("reduction_pct"):
        story.append(Paragraph(
            f"Complexity reduced by ~{translation['reduction_pct']}% "
            f"({translation.get('original_words', 0)} → {translation.get('plain_words', 0)} words)",
            styles["small_gray"]
        ))
        story.append(Spacer(1, 3 * mm))

    plain_text = translation.get("plain_text", "")
    for line in plain_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 2 * mm))
            continue
        safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if line.startswith("**") and line.endswith("**"):
            story.append(Paragraph(safe.replace("**", ""), styles["bold_label"]))
        elif line.startswith("•") or line.startswith("-") or line.startswith("*"):
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;{safe}", styles["body"]))
        else:
            story.append(Paragraph(safe, styles["body"]))


# ---------------------------------------------------------------------------
# Main builder function
# ---------------------------------------------------------------------------

def build_contract_pdf(data: dict) -> bytes:
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=28 * mm,
        bottomMargin=18 * mm,
        title="AI Legal Contract System Report",
        author="Maryam Mumtaz — AI Legal Contract System",
    )

    styles = _styles()
    story: list = []

    _cover_page(story, data, styles)
    _contract_text_section(story, data, styles)
    _risk_section(story, data, styles)
    _negotiation_section(story, data, styles)
    _plain_language_section(story, data, styles)

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
