import io
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_crisis_report_pdf(pipeline_data: dict) -> bytes:
    """Generates a highly clean, professional Crisis Mitigation Brief PDF report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0f172a')
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#64748b')
    )

    h2_style = ParagraphStyle(
        'SectionH2',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1e293b'),
        spaceBefore=14,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#334155')
    )

    bold_body_style = ParagraphStyle(
        'BodyDarkBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#0f172a')
    )

    story = []

    brand_name = pipeline_data.get("brand_name", "Brand")
    sev = pipeline_data.get("severity_classification", {})
    sev_level = sev.get("severity_level", "P1")
    risk_score = sev.get("risk_score_100", 80)

    # Header
    story.append(Paragraph(f"<b>CRISIS MANAGEMENT & BRAND PROTECTION BRIEF</b>", title_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"Target Brand: <b>{brand_name}</b> | Generated by AI Multi-Agent System | Maryam Mumtaz Portfolio", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#cbd5e1'), spaceBefore=0, spaceAfter=12))

    # Executive Summary Table
    table_data = [
        [
            Paragraph("<b>Severity Level</b>", bold_body_style),
            Paragraph(f"<font color='#dc2626'><b>{sev_level} ({sev.get('severity_title', '')})</b></font>", bold_body_style),
            Paragraph("<b>Risk Score</b>", bold_body_style),
            Paragraph(f"<b>{risk_score} / 100</b>", bold_body_style)
        ],
        [
            Paragraph("<b>Escalation Path</b>", bold_body_style),
            Paragraph(f"{sev.get('recommended_escalation', 'Executive Committee')}", body_style),
            Paragraph("<b>Action Priority</b>", bold_body_style),
            Paragraph(f"{sev.get('action_priority', 'Immediate PR response')}", body_style)
        ]
    ]

    t = Table(table_data, colWidths=[110, 160, 90, 180])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # Incident Overview
    story.append(Paragraph("1. Incident Context & Threat Evaluation", h2_style))
    story.append(Paragraph(f"<b>Context:</b> {pipeline_data.get('incident_context', '')}", body_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"<b>Classifier Assessment:</b> {sev.get('justification', '')}", body_style))
    story.append(Spacer(1, 10))

    # Sentiment & Media Tracker Summary
    story.append(Paragraph("2. Social & Media Sentiment Intelligence", h2_style))
    soc = pipeline_data.get("social_sentiment", {})
    news = pipeline_data.get("news_alert", {})

    sentiment_text = f"<b>Overall Sentiment Score:</b> {soc.get('overall_sentiment_score', 0)} | <b>Negative Mentions:</b> {soc.get('negative_mention_percentage', 0)}% | <b>24h Total Mentions:</b> {soc.get('total_mentions_24h', 0)}<br/>"
    sentiment_text += f"<b>Viral Risk Summary:</b> {soc.get('viral_risk_assessment', '')}<br/>"
    sentiment_text += f"<b>Mainstream Media Narrative:</b> {news.get('key_media_narrative', '')}"
    story.append(Paragraph(sentiment_text, body_style))
    story.append(Spacer(1, 10))

    # Press & PR Response Strategy
    pr = pipeline_data.get("pr_responses", {})
    press_rel = pr.get("press_release", {})
    story.append(Paragraph("3. Recommended Official Press Statement", h2_style))
    story.append(Paragraph(f"<b>Headline:</b> {press_rel.get('headline', '')}", bold_body_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph(f"<i>{press_rel.get('body', '')}</i>", body_style))
    story.append(Spacer(1, 10))

    # Stakeholder Messaging Summary
    stk = pipeline_data.get("stakeholder_communications", {})
    story.append(Paragraph("4. Multi-Stakeholder Action Directives", h2_style))
    
    stk_data = [
        [Paragraph("<b>Stakeholder</b>", bold_body_style), Paragraph("<b>Communication Focus & Action Plan</b>", bold_body_style)],
        [Paragraph("Customers", bold_body_style), Paragraph(f"<b>Subject:</b> {stk.get('customer_email', {}).get('subject', '')}", body_style)],
        [Paragraph("Enterprise VIP", bold_body_style), Paragraph(f"<b>Subject:</b> {stk.get('enterprise_client_email', {}).get('subject', '')}", body_style)],
        [Paragraph("Investors / Board", bold_body_style), Paragraph(f"<b>Subject:</b> {stk.get('investor_board_email', {}).get('subject', '')}", body_style)],
        [Paragraph("Internal Staff", bold_body_style), Paragraph(f"<b>Subject:</b> {stk.get('internal_team_email', {}).get('subject', '')}", body_style)]
    ]

    stk_table = Table(stk_data, colWidths=[120, 420])
    stk_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    story.append(stk_table)

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
